<?php

declare(strict_types=1);

namespace Antidot\Cli\Application;

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

final class Console extends Application
{
    /** @var InputInterface */
    private $input;

    public function __construct(string $name = 'AntiDot Framework Console Tool', string $version = '1.0.0')
    {
        $this->input = new ArgvInput();
        parent::__construct($name, $version);
    }

    public function run(InputInterface $input = null, OutputInterface $output = null)
    {
        return parent::run($input ?? $this->input, $output); // TODO: Change the autogenerated stub
    }

    public function getInput(): InputInterface
    {
        return $this->input;
    }
}
